### ISSUE TITLE
fix non-existings key 

### ISSUE THREAD

**Issue by mihakot** [locale-sphere/plugin#1]
при открытии fix non-existings keys, 
при удалении какой либо строки, и потом нажать `cancel` вместо `ok` 
и потом если опять открыть это окно, то  удаленная строка остается в списке и повторно ее не удалить. 
ошибок не пишет. просто пустой клик. 
исправляется только перечитыванием данных

**Comment by adelf** [comment]
I just removed the Cancel button) Thanks!
